### ISSUE TITLE
Behavior when referencing a Unis instance after it has already been referenced

### ISSUE THREAD

**Issue by gskip17** [periscope-ps/UNISrt#11]
Reproducible with the following

```
>>> rt = Runtime("http://um-ps01.osris.org:8888")
>>> rt2 = Runtime("http://um-ps01.osris.org:8888")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/lace-0.2.0-py3.5.egg/lace/logging/_log.py", line 235, in wrapper
  File "/usr/local/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/runtime/runtime.py", line 76, in __init__
    self._oal.preload()
  File "/usr/local/lib/python3.5/site-packages/lace-0.2.0-py3.5.egg/lace/logging/_log.py", line 235, in wrapper
  File "/usr/local/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/runtime/oal.py", line 86, in preload
    values = [c.load() for c in self._cache.values() if _p(c)]
  File "/usr/local/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/runtime/oal.py", line 86, in <listcomp>
    values = [c.load() for c in self._cache.values() if _p(c)]
  File "/usr/local/lib/python3.5/site-packages/lace-0.2.0-py3.5.egg/lace/logging/_log.py", line 235, in wrapper
  File "/usr/local/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/models/lists.py", line 82, in load
    self._complete_cache()
TypeError: <lambda>() missing 1 required positional argument: 's'
```

Ideally a developer should not be doing this given the way the new RT works, but legacy apps will fail with this and it might be something that shouldnt be a program killer.

**Comment by jemusser** [comment]
Resolved in 08de833978f9aa402832e73fd24285866240db6e
