### ISSUE TITLE
When in Deferred Mode the Runtime is not actually running Deferred Mode

### ISSUE THREAD

**Issue by gskip17** [periscope-ps/UNISrt#13]
Defer update flags and settings are applied to the Runtime but the Runtime does not behave like it is in Deferred mode.

**Comment by gskip17** [comment]
Pasting the trace 
Cant remember if this is part of the same issue.
But recall that accessing resources using operations such as `topology.domains[index] = most_recent_domain` was where this comes from.
```
Traceback (most recent call last):
  File "/user/gskipper/topology/ryu/osiris_main.py", line 457, in check_update_host_topology
    topology.domains[index] = most_recent_domain
  File "/usr/local/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/models/models.py", line 44, in __setitem__
    return self._obj._setitem(i, v, self._rt)
  File "/usr/local/lib/python3.5/site-packages/lace-0.2.0-py3.5.egg/lace/logging/_log.py", line 235, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/models/models.py", line 176, in _setitem
    self._update(self._rt_reference, ctx)
  File "/usr/local/lib/python3.5/site-packages/lace-0.2.0-py3.5.egg/lace/logging/_log.py", line 235, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/models/models.py", line 137, in _update
    self._rt_parent._update(ref, ctx)
  File "/usr/local/lib/python3.5/site-packages/lace-0.2.0-py3.5.egg/lace/logging/_log.py", line 235, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/models/models.py", line 263, in _update
    ctx.update(Context(self, ctx))
  File "/usr/local/lib/python3.5/site-packages/lace-0.2.0-py3.5.egg/lace/logging/_log.py", line 235, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/runtime/oal.py", line 50, in update
    asyncio.get_event_loop().run_until_complete(self._do_update([resource], resource.getCollection().name))
  File "/usr/local/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/runtime/oal.py", line 68, in _do_update
    list(map(self._pending.remove, resources))
  File "/usr/local/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/models/models.py", line 59, in __eq__
    return self._obj == other._obj
  File "/usr/local/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/models/models.py", line 84, in __getattribute__
    raise NotImplementedError # This is for debugging purposes, this line should never be reached
NotImplementedError
```

**Comment by naveenkumarmarri** [comment]
When I set the `proxy['defer_update'] = False` from `True`, the runtime is throwing the following error
```---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-2-c1555d589dda> in <module>()
      8 p7 = Port({"description":"port 7"})
      9 p8 = Port({"description":"port 8"})
---> 10 rt.insert(p1,commit=True)
     11 rt.insert(p2,commit=True)
     12 rt.insert(p3,commit=True)

~/anaconda3/envs/flange/lib/python3.5/site-packages/lace-0.2.0-py3.5.egg/lace/logging/_log.py in wrapper(*args, **kwargs)
    233             call_name = "{}.{}".format(cls, f.__name__)
    234             if trace._level == NOTSET and call_name not in trace._breakpoints:
--> 235                 return f(*args, **kwargs)
    236 
    237             if call_name in trace._breakpoints:

~/anaconda3/envs/flange/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/runtime/runtime.py in insert(self, resource, commit, publish_to)
     94     def insert(self, resource, commit=False, publish_to=None):
     95         if commit:
---> 96             self._oal.insert(resource).commit(publish_to=publish_to)
     97             return resource
     98         return self._oal.insert(resource)

~/anaconda3/envs/flange/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/models/models.py in f(*args, **kwargs)
     30                 def f(*args, **kwargs):
     31                     kwargs['ctx'] = self._rt
---> 32                     return v(*args, **kwargs)
     33                 return f
     34             return Context(v, self._rt) if isinstance(v, _unistype) else v

~/anaconda3/envs/flange/lib/python3.5/site-packages/lace-0.2.0-py3.5.egg/lace/logging/_log.py in wrapper(*args, **kwargs)
    233             call_name = "{}.{}".format(cls, f.__name__)
    234             if trace._level == NOTSET and call_name not in trace._breakpoints:
--> 235                 return f(*args, **kwargs)
    236 
    237             if call_name in trace._breakpoints:

~/anaconda3/envs/flange/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/models/models.py in commit(self, publish_to, ctx)
    293             self.__dict__['ts'] = int(time.time() * 1000000)
    294             self.__dict__['selfRef'] = "{}/{}/{}".format(url, self._rt_collection.name, self._getattribute('id', ctx))
--> 295             self._update('id', ctx)
    296     @trace.info("UnisObject")
    297     def extendSchema(self, n, v=None, ctx=None):

~/anaconda3/envs/flange/lib/python3.5/site-packages/lace-0.2.0-py3.5.egg/lace/logging/_log.py in wrapper(*args, **kwargs)
    233             call_name = "{}.{}".format(cls, f.__name__)
    234             if trace._level == NOTSET and call_name not in trace._breakpoints:
--> 235                 return f(*args, **kwargs)
    236 
    237             if call_name in trace._breakpoints:

~/anaconda3/envs/flange/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/models/models.py in _update(self, ref, ctx)
    261             self.__dict__['ts'] = int(time.time() * 1000000)
    262             self._rt_collection.update(self)
--> 263             ctx.update(Context(self, ctx))
    264     @trace.debug("UnisObject")
    265     def _get_reference(self, n):

~/anaconda3/envs/flange/lib/python3.5/site-packages/lace-0.2.0-py3.5.egg/lace/logging/_log.py in wrapper(*args, **kwargs)
    233             call_name = "{}.{}".format(cls, f.__name__)
    234             if trace._level == NOTSET and call_name not in trace._breakpoints:
--> 235                 return f(*args, **kwargs)
    236 
    237             if call_name in trace._breakpoints:

~/anaconda3/envs/flange/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/runtime/oal.py in update(self, resource)
     48                 self._pending.add(resource.getObject())
     49                 if not self.settings['proxy']['defer_update']:
---> 50                     asyncio.get_event_loop().run_until_complete(self._do_update([resource], resource.getCollection().name))
     51 
     52     @trace.debug("OAL")

~/anaconda3/envs/flange/lib/python3.5/asyncio/base_events.py in run_until_complete(self, future)
    465             raise RuntimeError('Event loop stopped before Future completed.')
    466 
--> 467         return future.result()
    468 
    469     def stop(self):

~/anaconda3/envs/flange/lib/python3.5/asyncio/futures.py in result(self)
    292             self._tb_logger = None
    293         if self._exception is not None:
--> 294             raise self._exception
    295         return self._result
    296 

~/anaconda3/envs/flange/lib/python3.5/asyncio/tasks.py in _step(***failed resolving arguments***)
    238                 # We use the `send` method directly, because coroutines
    239                 # don't have `__iter__` and `__next__` methods.
--> 240                 result = coro.send(None)
    241             else:
    242                 result = coro.throw(exc)

~/anaconda3/envs/flange/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/runtime/oal.py in _do_update(self, resources, collection)
     66                 r.__dict__["selfRef"] = resp["selfRef"]
     67                 self._cache[collection].updateIndex(r)
---> 68             list(map(self._pending.remove, resources))
     69             self._cache[collection].locked = False
     70 

~/anaconda3/envs/flange/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/models/models.py in __eq__(self, other)
     57     def __eq__(self, other):
     58         if isinstance(self, other.__class__):
---> 59             return self._obj == other._obj
     60         return self._obj == other
     61     def __hash__(self):

~/anaconda3/envs/flange/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/models/models.py in __getattribute__(self, n)
     82             if n in self._rt_restricted:
     83                 return self._getattribute(n, None)
---> 84             raise NotImplementedError # This is for debugging purposes, this line should never be reached
     85         return super(_unistype, self).__getattribute__(n)
     86     @trace.debug("unistype")

NotImplementedError: ```

**Comment by jemusser** [comment]
This issue actually pertains to two separate issues, created #14 for the inner context bug.
