### ISSUE TITLE
Object removal uses raw object instead of context

### ISSUE THREAD

**Issue by jemusser** [periscope-ps/UNISrt#14]
This is in reference to issue #13, which contains two separate issues.

```
Traceback (most recent call last):
  File "/user/gskipper/topology/ryu/osiris_main.py", line 457, in check_update_host_topology
    topology.domains[index] = most_recent_domain
  File "/usr/local/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/models/models.py", line 44, in __setitem__
    return self._obj._setitem(i, v, self._rt)
  File "/usr/local/lib/python3.5/site-packages/lace-0.2.0-py3.5.egg/lace/logging/_log.py", line 235, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/models/models.py", line 176, in _setitem
    self._update(self._rt_reference, ctx)
  File "/usr/local/lib/python3.5/site-packages/lace-0.2.0-py3.5.egg/lace/logging/_log.py", line 235, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/models/models.py", line 137, in _update
    self._rt_parent._update(ref, ctx)
  File "/usr/local/lib/python3.5/site-packages/lace-0.2.0-py3.5.egg/lace/logging/_log.py", line 235, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/models/models.py", line 263, in _update
    ctx.update(Context(self, ctx))
  File "/usr/local/lib/python3.5/site-packages/lace-0.2.0-py3.5.egg/lace/logging/_log.py", line 235, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/runtime/oal.py", line 50, in update
    asyncio.get_event_loop().run_until_complete(self._do_update([resource], resource.getCollection().name))
  File "/usr/local/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/runtime/oal.py", line 68, in _do_update
    list(map(self._pending.remove, resources))
  File "/usr/local/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/models/models.py", line 59, in __eq__
    return self._obj == other._obj
  File "/usr/local/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/models/models.py", line 84, in __getattribute__
    raise NotImplementedError # This is for debugging purposes, this line should never be reached
NotImplementedError
```

**Comment by jemusser** [comment]
Resolved in b9ecd326d375db705e320f5bf64264b40af4cca7
