### ISSUE TITLE
Removing a top level resource from UNIS

### ISSUE THREAD

**Issue by gskip17** [periscope-ps/UNISrt#32]
As per the docs -
``` 
ex)
rt = Runtime(my_url)
some_topology = rt.topologies[0]
some_topology.domains.remove(my_domain)
```

Works correctly, removing a domain obj of my choosing from the topology object/

However, removing a resource from the high level UNIS collection fails. 
``` 
ex)
rt = Runtime(my_url)
domain_to_remove = next(rt.domains.where({"name":"domain_to_delete"}))
rt.domains.remove(domain_to_remove)
```
Below is the trace.
```Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python3.6/site-packages/unisrt-1.0.dev0-py3.6.egg/unis/models/lists.py", line 206, in remove
    self._unis.delete(item.getSource(), item._getattribute('id', None))
  File "/usr/local/lib/python3.6/site-packages/unisrt-1.0.dev0-py3.6.egg/unis/models/models.py", line 52, in f
    return v(*args, **kwargs)
TypeError: _getattribute() got multiple values for argument 'ctx'```

**Comment by jemusser** [comment]
Resolved this issue in d414ab643edc4d962b6d6cd3174b6153a94be77c
