### ISSUE TITLE
Runtime throwing AttributeError

### ISSUE THREAD

**Issue by naveenkumarmarri** [periscope-ps/UNISrt#7]
Branch : `asyncio_fix`

description: When trying to connect instantiate runtime, it is throwing `AttributeError`

Following are the steps to reproduce the error
```python
>>> from unis import Runtime
>>> rt = Runtime('http://localhost:8888')
```
   
Error Log:

``` >>> rt = Runtime('http://localhost:8888')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/naveen/anaconda3/envs/flange/lib/python3.5/site-packages/lace-0.2.0-py3.5.egg/lace/logging/_log.py", line 235, in wrapper
  File "/home/naveen/anaconda3/envs/flange/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/runtime/runtime.py", line 76, in __init__
    self._oal.preload()
  File "/home/naveen/anaconda3/envs/flange/lib/python3.5/site-packages/lace-0.2.0-py3.5.egg/lace/logging/_log.py", line 235, in wrapper
  File "/home/naveen/anaconda3/envs/flange/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/runtime/oal.py", line 86, in preload
    values = [c.load() for c in self._cache.values() if _p(c)]
  File "/home/naveen/anaconda3/envs/flange/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/runtime/oal.py", line 86, in <listcomp>
    values = [c.load() for c in self._cache.values() if _p(c)]
  File "/home/naveen/anaconda3/envs/flange/lib/python3.5/site-packages/lace-0.2.0-py3.5.egg/lace/logging/_log.py", line 235, in wrapper
  File "/home/naveen/anaconda3/envs/flange/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/models/lists.py", line 82, in load
    self._complete_cache()
  File "/home/naveen/anaconda3/envs/flange/lib/python3.5/site-packages/lace-0.2.0-py3.5.egg/lace/logging/_log.py", line 235, in wrapper
  File "/home/naveen/anaconda3/envs/flange/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/models/lists.py", line 205, in _proto_complete_cache
    self._get_next()
  File "/home/naveen/anaconda3/envs/flange/lib/python3.5/site-packages/lace-0.2.0-py3.5.egg/lace/logging/_log.py", line 235, in wrapper
  File "/home/naveen/anaconda3/envs/flange/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/models/lists.py", line 225, in _proto_get_next
    self.append(model(result))
  File "/home/naveen/anaconda3/envs/flange/lib/python3.5/site-packages/lace-0.2.0-py3.5.egg/lace/logging/_log.py", line 235, in wrapper
  File "/home/naveen/anaconda3/envs/flange/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/models/lists.py", line 110, in append
    self._serve(Events.new, item)
  File "/home/naveen/anaconda3/envs/flange/lib/python3.5/site-packages/lace-0.2.0-py3.5.egg/lace/logging/_log.py", line 235, in wrapper
  File "/home/naveen/anaconda3/envs/flange/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/models/lists.py", line 200, in _serve
    f(ctx)
  File "/home/naveen/anaconda3/envs/flange/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/services/abstract.py", line 9, in nf
    kwargs[fn](self, resource)
  File "/home/naveen/anaconda3/envs/flange/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/services/graph.py", line 72, in new
    self.runtime.graph.edges.append((resource.endpoints.source.node, resource.endpoints.sink.node))
  File "/home/naveen/anaconda3/envs/flange/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/models/models.py", line 28, in __getattribute__
    v = self._obj._getattribute(n, self._rt)
  File "/home/naveen/anaconda3/envs/flange/lib/python3.5/site-packages/lace-0.2.0-py3.5.egg/lace/logging/_log.py", line 235, in wrapper
  File "/home/naveen/anaconda3/envs/flange/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/models/models.py", line 86, in _getattribute
    v = super(_unistype, self).__getattribute__(n)
AttributeError: 'Port' object has no attribute 'node')  ```

**Comment by naveenkumarmarri** [comment]
Fixed by latest commit to `async_io` branch
