### ISSUE TITLE
Port Object Referenced by two or more nodes.

### ISSUE THREAD

**Issue by gskip17** [periscope-ps/UNISrt#9]
I understand why this might be an error, but there I dont think this should cause the RT to fail.

```rt = Runtime("http://um-ps01.osris.org:8888", proxy = {'subscribe':False, 'defer_update':True})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/lace-0.2.0-py3.5.egg/lace/logging/_log.py", line 235, in wrapper
  File "/usr/local/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/runtime/runtime.py", line 76, in __init__
    self._oal.preload()
  File "/usr/local/lib/python3.5/site-packages/lace-0.2.0-py3.5.egg/lace/logging/_log.py", line 235, in wrapper
  File "/usr/local/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/runtime/oal.py", line 86, in preload
    values = [c.load() for c in self._cache.values() if _p(c)]
  File "/usr/local/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/runtime/oal.py", line 86, in <listcomp>
    values = [c.load() for c in self._cache.values() if _p(c)]
  File "/usr/local/lib/python3.5/site-packages/lace-0.2.0-py3.5.egg/lace/logging/_log.py", line 235, in wrapper
  File "/usr/local/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/models/lists.py", line 82, in load
    self._complete_cache()
  File "/usr/local/lib/python3.5/site-packages/lace-0.2.0-py3.5.egg/lace/logging/_log.py", line 235, in wrapper
  File "/usr/local/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/models/lists.py", line 205, in _proto_complete_cache
    self._get_next()
  File "/usr/local/lib/python3.5/site-packages/lace-0.2.0-py3.5.egg/lace/logging/_log.py", line 235, in wrapper
  File "/usr/local/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/models/lists.py", line 225, in _proto_get_next
    self.append(model(result))
  File "/usr/local/lib/python3.5/site-packages/lace-0.2.0-py3.5.egg/lace/logging/_log.py", line 235, in wrapper
  File "/usr/local/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/models/lists.py", line 110, in append
    self._serve(Events.new, item)
  File "/usr/local/lib/python3.5/site-packages/lace-0.2.0-py3.5.egg/lace/logging/_log.py", line 235, in wrapper
  File "/usr/local/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/models/lists.py", line 200, in _serve
    f(ctx)
  File "/usr/local/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/services/abstract.py", line 9, in nf
    kwargs[fn](self, resource)
  File "/usr/local/lib/python3.5/site-packages/unisrt-1.0.dev0-py3.5.egg/unis/services/graph.py", line 62, in new
    raise AttributeError("Port object referenced by two or more Nodes")
AttributeError: Port object referenced by two or more Nodes```

**Comment by gskip17** [comment]
Is there a one liner I can use to determine what the port(s) in question is/are? This would help me debug this. If not I can just ctrl+F through unis.

**Comment by jemusser** [comment]
This may be caused by using the same uuid for multiple instances of a node (note to self:  Look into what happens when a new node is created with the same id as an already existing uuid).

**Comment by gskip17** [comment]
I think this is exactly the case, this is how the topo app did things when I picked it up. I am pretty sure this is a side effect of needing to handle defer updates with update and flush calls depending on the operation. If 'defer update' is fixed in the latest RT I can start refactoring on that, but in the meantime it would be nice to suppress this warning.
